# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3  # Number of replicas/pods to maintain
  selector:
    matchLabels:
      app: myapp  # Label to match pods
  template:
    metadata:
      labels:
        app: myapp  # Label for pods
    spec:
      containers:
      - name: myapp-container
        image: ggezskrub/nodeapp:latest  # Replace with your container image details
        ports:
        - containerPort: 3000  # Port on which the container listens

#

# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service  # Updated service name
  
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
