# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment  # Updated deployment name
  namespace: default
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: ggezskrub/nodeapp:latest
        ports:
        - containerPort: 3000

---

# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service  # Updated service name
  namespace: default
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
